routes/web.php
<?php

use App\Http\Controllers\EstudianteController;
use App\Http\Controllers\ProfileController;
use App\Livewire\Estudiante\Edit;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Ruta de recursos para el estudiante
    // Llama al controlador Estudiante de Laravel
    
    Route::resource('estudiantes', EstudianteController::class);

    // Ruta tipo get para actualizar un estudiante por medio de su id
    // Llama al componente Edit de livewire
    Route::get('estudiantes/{estudiante}/edit', Edit::class)->name('estudiantes.edit');
});

require __DIR__.'/auth.php';

app/Models/Estudiante.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Estudiante extends Model implements HasMedia
{
    use HasFactory;
    use InteractsWithMedia;
    protected $fillable = [
        'seccion_id',
        'clase_id',
        'nombre',
        'correo'
    ];

    public function secciones(){
        return $this->belongsTo(Secciones::class, 'seccion_id');
    }

    public function clases(){
        return $this->belongsTo(Clases::class, 'clase_id');
    }
}

app/Http/Controllers/EstudianteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class EstudianteController extends Controller
{
    public function index(){
        return view('estudiante.index');
    }
    public function create(){
        return view('estudiante.create');
    }
}

app/Livewire/Estudiante/Create.php
<?php

namespace App\Livewire\Estudiante;

use App\Livewire\Forms\StoreEstudiante;
use App\Models\Clases;
use App\Models\Secciones;
use Livewire\Attributes\Validate;
use Livewire\Component;
use Livewire\WithFileUploads;

class Create extends Component
{
    use WithFileUploads;

    public StoreEstudiante $form;

    #[Validate('required')]
    public $clase_id;

    public $secciones = [];

    public function render()
    {
        return view('livewire.estudiante.create', [
            'clases' => Clases::all()
        ]);
    }

    public function guardar()
    {
        $this->validate();

        $this->form->guardar(clase_id: $this->clase_id);

        return redirect()->route('estudiantes.index')
            ->with('estatus', 'Estudiante creado con éxito');
    }

    public function updatedClaseId($value)
    {
        $this->secciones = Secciones::where('clase_id', $value)->get();
    }
}

app/Livewire/Estudiante/Edit.php
<?php

namespace App\Livewire\Estudiante;

use App\Livewire\Forms\UpdateEstudiante;
use App\Models\Clases;
use App\Models\Estudiante;
use App\Models\Secciones;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Validate;
use Livewire\WithFileUploads;
use Livewire\Component;

class Edit extends Component
{
    use WithFileUploads;

    public Estudiante $estudiante;

    public UpdateEstudiante $form;

    #[Validate('required')]
    public $clase_id;

    public $secciones = [];

    public function mount()
    {

        $this->form->setStudent($this->estudiante);

        $this->fill(
            $this->estudiante->only('clase_id')
        );

        $this->secciones = Secciones::where('clase_id', $this->estudiante->clase_id)->get();
    }

    #[Layout('layouts.app')]
    public function render()
    {
        return view('livewire.estudiante.edit', [
            'clases' => Clases::all()
        ]);
    }

    public function updatedClaseId($value)
    {
        $this->secciones = Secciones::where('clase_id', $value)->get();
    }

    public function actualizar()
    {
        $this->validate();

        $this->form->actualizar($this->clase_id);

        return redirect()->route('estudiantes.index')
            ->with('estatus', 'El estudiante ha sido actualizado con éxito');
    }
}

app/Livewire/Estudiante/Index.php
<?php

namespace App\Livewire\Estudiante;

use App\Models\Estudiante;
use Livewire\Component;
use Livewire\WithPagination;

class Index extends Component
{
    use WithPagination;
    public function render()
    {
        return view('livewire.estudiante.index', [
            'estudiantes' => Estudiante::paginate(10),
        ]);
    }

    public function eliminar(Estudiante $estudiante)
    {
        $estudiante->delete();

        return redirect()->route('estudiantes.index')
            ->with('estatus', 'El estudiante ha sido eliminado con éxito');
    }

    
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/estudiante/create.blade.php
{{-- Vista que extiende del layout app.blade.php --}}
{{-- Contiene incrustado un componente de livewire --}}

<x-app-layout>
    <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        <div class="lg:grid lg:grid-cols-12 lg:gap-x-5">
            <div class="space-y-6 sm:px-6 lg:px-0 lg:col-span-12">

                {{-- Componente de livewire --}}
                
                @livewire('estudiante.create')
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/estudiante/index.blade.php
{{-- Vista que extiende del layout app.blade.php --}}
{{-- Contiene incrustado un componente de livewire --}}

<x-app-layout>
    <div class="bg-gray-100 py-10">
        <div class="mx-auto max-w-7xl">
            <div class="px-4 sm:px-6 lg:px-8">
                <div class="sm:flex sm:items-center">
                    <div class="sm:flex-auto">
                        <h1 class="text-xl font-semibold text-gray-900">
                            Estudiantes
                        </h1>
                        <p class="mt-2 text-sm text-gray-700">
                            Lista de todos los estudiantes
                        </p>
                    </div>

                    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">

                        {{-- Enlace para ir a la vista de crear un nuevo registro --}}

                        <a href="{{ route('estudiantes.create') }}" as="button"
                            class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto">
                            Nuevo Estudiante
                        </a>
                    </div>
                </div>

                {{-- Componente de livewire --}}
                
                @livewire('estudiante.index')
            </div>
        </div>
    </div>
</x-app-layout>